name: GitHub Actions Demo
run-name: Testing GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  example-simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1.
        run: echo "This job is automatically triggered by a push event."
      - name: Step 2.
        run: echo "Step2. Another example of a step"
      - name: Step 3. Check out repository code
        uses: actions/checkout@v3
      - name: Step 3.
        run: echo "Step 4. The repository has been cloned to the runner."
      - name: Step 4. List files in the repository
        run: ls
      - name: Step 5.
        run: echo "Job is finished."